name: "P6 GHA: Deploys a NextJS Static Site to S3"
description: "P6 GHA: Deploys a NextJS Static Site to S3"
author: "Philip M. Gollucci"
inputs:
  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "us-east-1"
  aws_role:
    description: "AWS role to assume"
    required: true
  aws_session_name:
    description: "Session name for the AWS role"
    required: true
  cdk_deploy_account:
    description: "AWS CDK deploy account"
    required: true
  cdk_deploy_region:
    description: "AWS CDK deploy region"
    required: true
  bucket_name:
    description: "S3 bucket name"
    required: true
  cloudfront_distribution_id:
    description: "CloudFront distribution ID"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0
    - name: Node
      uses: p6m7g8-actions/node-setup@main
    - name: Disable Next.js Telemetry
      shell: bash
      run: echo "NEXT_TELEMETRY_DISABLED=1" >> "$GITHUB_ENV"
    - name: Run build
      shell: bash
      run: |
        env | sort
        pnpm run build
    - name: Assume role using OIDC
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: ${{ inputs.aws_session_name }}
    - name: Deploy to S3
      shell: bash
      run: aws s3 sync out s3://${{ inputs.bucket_name }} --no-progress --follow-symlinks --delete --region ${{ inputs.cdk_deploy_region }}
    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v2.4
      env:
        AWS_REGION: ${{ inputs.cdk_deploy_region }}
        DISTRIBUTION: ${{ inputs.cloudfront_distribution_id }}
        PATHS: "/*"
